config/routes.rb
Rails.application.routes.draw do
  resources :provinces

  root to: 'home#index'

  get 'missing_email', to: 'home#missing_email'

  get 'alphabetized', to: 'home#alphabetized'
  
  post 'add_to_call_list/:id',
       to: 'home#add_customer_to_call_list',
       as: 'add_to_call_list'
       
  delete 'remove_from_call_list/:id',
         to: 'home#remove_customer_from_call_list',
         as: 'remove_from_call_list'
         
  post 'clear_to_call_list',
       to: 'home#clear_to_call_list',
       as: 'clear_to_call_list'

  resources :customers

end

app/models/customer.rb
class Customer < ActiveRecord::Base
  belongs_to :province
  validates :full_name, presence: true
end

app/models/province.rb
class Province < ActiveRecord::Base
  has_many :customers
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  def customers_to_call
    session[:customers_to_call] ||= []
    return session[:customers_to_call].map do |id|
      Customer.find(id)
    end
  end
  helper_method :customers_to_call
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  before_action :set_customer, only: [:show, :edit, :update, :destroy]

  # GET /customers
  # GET /customers.json
  def index
    @customers = Customer.all
  end

  # GET /customers/1
  # GET /customers/1.json
  def show
  end

  # GET /customers/new
  def new
    @customer = Customer.new
    @provinces = Province.all
  end

  # GET /customers/1/edit
  def edit
    @provinces = Province.all
  end

  # POST /customers
  # POST /customers.json
  def create
    @customer = Customer.new(customer_params)

    respond_to do |format|
      if @customer.save
        format.html { redirect_to @customer, notice: 'Customer was successfully created.' }
        format.json { render :show, status: :created, location: @customer }
      else
        format.html { render :new }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /customers/1
  # PATCH/PUT /customers/1.json
  def update
    respond_to do |format|
      if @customer.update(customer_params)
        format.html { redirect_to @customer, notice: 'Customer was successfully updated.' }
        format.json { render :show, status: :ok, location: @customer }
      else
        format.html { render :edit }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /customers/1
  # DELETE /customers/1.json
  def destroy
    @customer.destroy
    respond_to do |format|
      format.html { redirect_to root_url, notice: 'Customer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_customer
      @customer = Customer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def customer_params
      params.require(:customer).permit(:full_name, :phone_number, :email_address, :image, :notes, :province_id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @customers = Customer.all
  end

  def missing_email
    @customers = Customer.where('email_address is NULL OR email_address = ""')
  end

  def alphabetized
    @customers = Customer.order(:full_name)
  end
  
  def add_customer_to_call_list
    session[:customers_to_call] << params[:id].to_i
    session[:customers_to_call].uniq!
    redirect_to :back
  end
  
  def remove_customer_from_call_list
    session[:customers_to_call].delete(params[:id].to_i)
    redirect_to :back
  end
  
  def clear_to_call_list
    session[:customers_to_call] = nil
    redirect_to :back
  end
end

app/controllers/provinces_controller.rb
class ProvincesController < ApplicationController
  before_action :set_province, only: [:show, :edit, :update, :destroy]

  # GET /provinces
  # GET /provinces.json
  def index
    @provinces = Province.all
  end

  # GET /provinces/1
  # GET /provinces/1.json
  def show
  end

  # GET /provinces/new
  def new
    @province = Province.new
  end

  # GET /provinces/1/edit
  def edit
  end

  # POST /provinces
  # POST /provinces.json
  def create
    @province = Province.new(province_params)

    respond_to do |format|
      if @province.save
        format.html { redirect_to @province, notice: 'Province was successfully created.' }
        format.json { render :show, status: :created, location: @province }
      else
        format.html { render :new }
        format.json { render json: @province.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /provinces/1
  # PATCH/PUT /provinces/1.json
  def update
    respond_to do |format|
      if @province.update(province_params)
        format.html { redirect_to @province, notice: 'Province was successfully updated.' }
        format.json { render :show, status: :ok, location: @province }
      else
        format.html { render :edit }
        format.json { render json: @province.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /provinces/1
  # DELETE /provinces/1.json
  def destroy
    @province.destroy
    respond_to do |format|
      format.html { redirect_to provinces_url, notice: 'Province was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_province
      @province = Province.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def province_params
      params.require(:province).permit(:name, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/provinces_helper.rb
module ProvincesHelper
end

app/views/customers/_customer.html.slim
.customer
  .actions
    span = link_to 'x', customer, method: :delete, data: { confirm: 'Are you sure?' }
    span = link_to 'edit', edit_customer_path(customer)
    - if customers_to_call.include?(customer)
      span = link_to 'unflag', remove_from_call_list_path(customer), method: :delete
    - else
      span = link_to 'to call', add_to_call_list_path(customer), method: :post
  h2 = customer.full_name
  - if customer.image.present?
    p = image_tag customer.image, width: 200
  p
    strong Province: 
    - if customer.province.present?
      = customer.province.name
    - else
      | None
  p
    strong Phone number: 
    = customer.phone_number
  p
    strong Email: 
    = mail_to customer.email_address
  p
    strong Notes: 
    = customer.notes

app/views/customers/_form.html.slim
= form_for @customer do |f|
  - if @customer.errors.any?
    #error_explanation
      h2 = "#{pluralize(@customer.errors.count, "error")} prohibited this customer from being saved:"
      ul
        - @customer.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :full_name
    = f.text_field :full_name
  .field
    = f.label :phone_number
    = f.text_field :phone_number
  .field
    = f.label :email_address
    = f.text_field :email_address
  .field
    = f.label :image
    = f.text_field :image
  .field
    = f.label :province
    = f.select :province_id, options_from_collection_for_select(@provinces, 'id', 'name')
  .field
    = f.label :notes
    = f.text_area :notes
  .actions = f.submit

app/views/customers/edit.html.slim
h1 Editing customer

== render 'form'

= link_to 'Show', @customer
'|
= link_to 'Back', customers_path

app/views/customers/index.html.slim
h1 Listing customers

table
  thead
    tr
      th Full name
      th Phone number
      th Email address
      th Image
      th Notes
      th
      th
      th

  tbody
    - @customers.each do |customer|
      tr
        td = customer.full_name
        td = customer.phone_number
        td = customer.email_address
        td = customer.image
        td = customer.notes
        td = link_to 'Show', customer
        td = link_to 'Edit', edit_customer_path(customer)
        td = link_to 'Destroy', customer, data: {:confirm => 'Are you sure?'}, :method => :delete

br

= link_to 'New Customer', new_customer_path

app/views/customers/new.html.slim
h1 New customer

== render 'form'

= link_to 'Back', customers_path

app/views/customers/show.html.slim
p#notice = notice

= render @customer

= link_to 'Edit', edit_customer_path(@customer)
'|
= link_to 'Back', customers_path

app/views/home/alphabetized.html.slim
h1 Alphabetized Customers

= render @customers

app/views/home/index.html.slim
h1 All Customers

.customers 
    = render @customers

app/views/home/missing_email.html.slim
h1 Customers Missing Email Addresses

= render @customers

app/views/layouts/application.html.slim
doctype html
html
  head
    title Customer Relations Manager
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  body
    #wrapper
      header
        nav
          ul
            li = link_to 'Home', root_path
            li = link_to 'Missing Email', missing_email_path
            li = link_to 'Alphabetized', alphabetized_path
            li = link_to 'Provinces Admin', provinces_path
            li = link_to 'Customer Admin', customers_path
  
      - unless customers_to_call.empty?
        = render 'shared/customers_to_call'
      == yield

app/views/provinces/_form.html.slim
= form_for @province do |f|
  - if @province.errors.any?
    #error_explanation
      h2 = "#{pluralize(@province.errors.count, "error")} prohibited this province from being saved:"
      ul
        - @province.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :description
    = f.text_area :description
  .actions = f.submit

app/views/provinces/edit.html.slim
h1 Editing province

== render 'form'

= link_to 'Show', @province
'|
= link_to 'Back', provinces_path

app/views/provinces/index.html.slim
h1 Listing provinces

table
  thead
    tr
      th Name
      th Description
      th
      th
      th

  tbody
    - @provinces.each do |province|
      tr
        td = province.name
        td = province.description
        td = link_to 'Show', province
        td = link_to 'Edit', edit_province_path(province)
        td = link_to 'Destroy', province, data: {:confirm => 'Are you sure?'}, :method => :delete

br

= link_to 'New Province', new_province_path

app/views/provinces/new.html.slim
h1 New province

== render 'form'

= link_to 'Back', provinces_path

app/views/provinces/show.html.slim
p#notice = notice

p
  strong Name:
  = @province.name
p
  strong Description:
  = @province.description

= link_to 'Edit', edit_province_path(@province)
'|
= link_to 'Back', provinces_path

app/views/shared/_customers_to_call.html.slim
#customers_to_call
  h2 Customers to Call
  - customers_to_call.each do |customer|
    p = link_to customer.full_name, customer
  p= link_to 'Clear List', clear_to_call_list_path, method: :post